# Generated by Django 4.1.1 on 2022-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('idade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email', models.TextField(max_length=100)),
                ('ativo', models.CharField(max_length=2)),
            ],
        ),
    ]
