# Generated by Django 4.1.1 on 2022-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaInicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='ativo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.TextField(max_length=50),
        ),
    ]
