# Generated by Django 4.1.1 on 2022-09-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaInicial', '0002_alter_cadastro_ativo_alter_cadastro_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
