# Generated by Django 4.1.1 on 2022-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaInicial', '0003_alter_cadastro_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
